"use server";

import { revalidatePath } from "next/cache";

import { getScopedSupabase } from "@/lib/auth/scoped-supabase";
import { WINSTON_FREE_DAILY_MESSAGE_CAP, WINSTON_MONTHLY_TOKEN_LIMIT } from "@/lib/ai/constants";
import { countChatExchangesOnLocalDay } from "@/lib/ai/free-chat-cap";
import type { ActionResult } from "@/lib/tasks/types";
import type {
  AIConversation,
  ActiveProject,
  ConversationMessage,
  MonthlyUsage,
} from "@/lib/ai/types";
import {
  getScopeKeyTitle,
  isWinstonScopeKey,
} from "@/lib/winston/scope";

// ─── Legacy: single-conversation history ─────────────────────────────────────

export async function getConversationHistory(): Promise<
  ActionResult<ConversationMessage[]>
> {
  const { supabase, userId } = await getScopedSupabase();

  const { data, error } = await supabase
    .from("ai_conversation_messages")
    .select("id, role, content, created_at")
    .eq("user_id", userId)
    .order("created_at", { ascending: true })
    .limit(50);

  if (error) {
    console.error("getConversationHistory:", error);
    return { success: false, error: error.message };
  }

  return { success: true, data: (data ?? []) as ConversationMessage[] };
}

// ─── Monthly usage ────────────────────────────────────────────────────────────

export type WinstonSettingsUsage = MonthlyUsage;

export async function getMonthlyUsage(): Promise<ActionResult<WinstonSettingsUsage>> {
  const { supabase, userId } = await getScopedSupabase();

  const monthStart = new Date();
  monthStart.setDate(1);
  monthStart.setHours(0, 0, 0, 0);

  const resetDate = new Date(monthStart);
  resetDate.setMonth(resetDate.getMonth() + 1);

  const { data, error } = await supabase
    .from("ai_usage_log")
    .select("feature, input_tokens, output_tokens")
    .eq("user_id", userId)
    .gte("created_at", monthStart.toISOString());

  if (error) {
    console.error("getMonthlyUsage:", error);
    return { success: false, error: error.message };
  }

  let chatTokens = 0;
  let digestTokens = 0;
  let emailDraftTokens = 0;
  let emailPicksDraftTokens = 0;
  let propertyInsightsTokens = 0;
  let portalTriageTokens = 0;

  for (const row of data ?? []) {
    const tokens = (row.input_tokens ?? 0) + (row.output_tokens ?? 0);
    if (row.feature === "chat") chatTokens += tokens;
    else if (row.feature === "digest") digestTokens += tokens;
    else if (row.feature === "email_draft") emailDraftTokens += tokens;
    else if (row.feature === "email_picks_draft") emailPicksDraftTokens += tokens;
    else if (row.feature === "property_insights") propertyInsightsTokens += tokens;
    else if (row.feature === "portal_triage") portalTriageTokens += tokens;
  }

  const userInitiatedTokens = chatTokens + emailDraftTokens;
  const autoGeneratedTokens =
    digestTokens +
    emailPicksDraftTokens +
    propertyInsightsTokens +
    portalTriageTokens;
  const total = userInitiatedTokens;
  const limit = WINSTON_MONTHLY_TOKEN_LIMIT;
  const percentage = Math.min(100, Math.round((total / limit) * 100));

  return {
    success: true,
    data: {
      chatTokens,
      digestTokens,
      emailDraftTokens,
      emailPicksDraftTokens,
      propertyInsightsTokens,
      userInitiatedTokens,
      autoGeneratedTokens,
      total,
      limit,
      percentage,
      resetDate: resetDate.toISOString(),
    },
  };
}

// ─── Conversations ────────────────────────────────────────────────────────────

export async function getConversations(): Promise<
  ActionResult<AIConversation[]>
> {
  const { supabase, userId } = await getScopedSupabase();

  const { data, error } = await supabase
    .from("ai_conversations")
    .select(
      "id, user_id, title, project_id, note_id, scope_key, created_at, updated_at, projects(project_name)"
    )
    .eq("user_id", userId)
    .is("note_id", null)
    .is("scope_key", null)
    .order("updated_at", { ascending: false })
    .limit(50);

  if (error) {
    console.error("getConversations:", error);
    return { success: false, error: error.message };
  }

  const conversations: AIConversation[] = (data ?? []).map((row) => ({
    id: row.id,
    user_id: row.user_id,
    title: row.title,
    project_id: row.project_id ?? null,
    project_name:
      row.projects && !Array.isArray(row.projects)
        ? (row.projects as { project_name: string }).project_name
        : null,
    note_id: row.note_id ?? null,
    scope_key: row.scope_key ?? null,
    created_at: row.created_at,
    updated_at: row.updated_at,
  }));

  return { success: true, data: conversations };
}

export async function createConversation(
  projectId?: string
): Promise<ActionResult<AIConversation>> {
  const { supabase, userId } = await getScopedSupabase();

  let title = "New conversation";

  if (projectId) {
    const { data: project } = await supabase
      .from("projects")
      .select("project_name")
      .eq("id", projectId)
      .eq("user_id", userId)
      .maybeSingle();
    if (project?.project_name) {
      title = `${project.project_name} chat`;
    }
  }

  const { data, error } = await supabase
    .from("ai_conversations")
    .insert({
      user_id: userId,
      title,
      project_id: projectId ?? null,
    })
    .select("id, user_id, title, project_id, created_at, updated_at")
    .single();

  if (error) {
    console.error("createConversation:", error);
    return { success: false, error: error.message };
  }

  return {
    success: true,
    data: {
      id: data.id,
      user_id: data.user_id,
      title: data.title,
      project_id: data.project_id ?? null,
      project_name: null,
      note_id: null,
      scope_key: null,
      created_at: data.created_at,
      updated_at: data.updated_at,
    },
  };
}

const CONVERSATION_ROW_SELECT =
  "id, user_id, title, project_id, note_id, scope_key, created_at, updated_at";

function toAIConversation(
  row: {
    id: string;
    user_id: string;
    title: string;
    project_id: string | null;
    note_id?: string | null;
    scope_key?: string | null;
    created_at: string;
    updated_at: string;
  },
  extras?: { project_name?: string | null; note_id?: string | null }
): AIConversation {
  return {
    id: row.id,
    user_id: row.user_id,
    title: row.title,
    project_id: row.project_id ?? null,
    project_name: extras?.project_name ?? null,
    note_id: extras?.note_id ?? row.note_id ?? null,
    scope_key: row.scope_key ?? null,
    created_at: row.created_at,
    updated_at: row.updated_at,
  };
}

export async function getOrCreateNoteConversation(
  noteId: string
): Promise<
  ActionResult<{
    conversation: AIConversation;
    messages: ConversationMessage[];
  }>
> {
  const { supabase, userId } = await getScopedSupabase();

  const { data: note, error: noteError } = await supabase
    .from("notes")
    .select("id, title")
    .eq("id", noteId)
    .eq("user_id", userId)
    .maybeSingle();

  if (noteError) {
    console.error("getOrCreateNoteConversation note:", noteError);
    return { success: false, error: noteError.message };
  }

  if (!note) {
    return { success: false, error: "Note not found" };
  }

  const { data: existing, error: existingError } = await supabase
    .from("ai_conversations")
    .select(CONVERSATION_ROW_SELECT)
    .eq("user_id", userId)
    .eq("note_id", noteId)
    .maybeSingle();

  if (existingError) {
    console.error("getOrCreateNoteConversation find:", existingError);
    return { success: false, error: existingError.message };
  }

  let conversationRow = existing;

  if (!conversationRow) {
    const title = note.title.trim()
      ? `${note.title.trim().slice(0, 60)} brainstorm`
      : "Note brainstorm";

    const { data: created, error: createError } = await supabase
      .from("ai_conversations")
      .insert({
        user_id: userId,
        title,
        note_id: noteId,
      })
      .select(CONVERSATION_ROW_SELECT)
      .single();

    if (createError) {
      if (createError.code === "23505") {
        const { data: raced } = await supabase
          .from("ai_conversations")
          .select(CONVERSATION_ROW_SELECT)
          .eq("user_id", userId)
          .eq("note_id", noteId)
          .maybeSingle();
        if (!raced) {
          console.error("getOrCreateNoteConversation race miss:", createError);
          return { success: false, error: createError.message };
        }
        conversationRow = raced;
      } else {
        console.error("getOrCreateNoteConversation create:", createError);
        return { success: false, error: createError.message };
      }
    } else {
      conversationRow = created;
    }
  }

  if (!conversationRow) {
    return { success: false, error: "Failed to open conversation" };
  }

  const messagesResult = await getConversationMessages(conversationRow.id);
  if (!messagesResult.success) {
    return { success: false, error: messagesResult.error };
  }

  return {
    success: true,
    data: {
      conversation: toAIConversation(conversationRow, {
        note_id: conversationRow.note_id ?? noteId,
      }),
      messages: messagesResult.data ?? [],
    },
  };
}

/**
 * Get or create a page-level scoped brainstorm conversation (Calendar, Content, …).
 * Isolated from note_id / project_id / other scope_key threads.
 */
export async function getOrCreateScopedConversation(
  scopeKey: string
): Promise<
  ActionResult<{
    conversation: AIConversation;
    messages: ConversationMessage[];
  }>
> {
  if (!isWinstonScopeKey(scopeKey)) {
    return { success: false, error: "Invalid conversation scope" };
  }

  const { supabase, userId } = await getScopedSupabase();

  const { data: existing, error: existingError } = await supabase
    .from("ai_conversations")
    .select(CONVERSATION_ROW_SELECT)
    .eq("user_id", userId)
    .eq("scope_key", scopeKey)
    .maybeSingle();

  if (existingError) {
    console.error("getOrCreateScopedConversation find:", existingError);
    return { success: false, error: existingError.message };
  }

  let conversationRow = existing;

  if (!conversationRow) {
    const { data: created, error: createError } = await supabase
      .from("ai_conversations")
      .insert({
        user_id: userId,
        title: getScopeKeyTitle(scopeKey),
        scope_key: scopeKey,
      })
      .select(CONVERSATION_ROW_SELECT)
      .single();

    if (createError) {
      if (createError.code === "23505") {
        const { data: raced } = await supabase
          .from("ai_conversations")
          .select(CONVERSATION_ROW_SELECT)
          .eq("user_id", userId)
          .eq("scope_key", scopeKey)
          .maybeSingle();
        if (!raced) {
          console.error(
            "getOrCreateScopedConversation race miss:",
            createError
          );
          return { success: false, error: createError.message };
        }
        conversationRow = raced;
      } else {
        console.error("getOrCreateScopedConversation create:", createError);
        return { success: false, error: createError.message };
      }
    } else {
      conversationRow = created;
    }
  }

  if (!conversationRow) {
    return { success: false, error: "Failed to open conversation" };
  }

  const messagesResult = await getConversationMessages(conversationRow.id);
  if (!messagesResult.success) {
    return { success: false, error: messagesResult.error };
  }

  return {
    success: true,
    data: {
      conversation: toAIConversation(conversationRow),
      messages: messagesResult.data ?? [],
    },
  };
}

export async function updateConversationTitle(
  id: string,
  title: string
): Promise<ActionResult> {
  const { supabase, userId } = await getScopedSupabase();

  const { error } = await supabase
    .from("ai_conversations")
    .update({ title })
    .eq("id", id)
    .eq("user_id", userId);

  if (error) {
    console.error("updateConversationTitle:", error);
    return { success: false, error: error.message };
  }

  return { success: true };
}

export async function deleteConversation(id: string): Promise<ActionResult> {
  const { supabase, userId } = await getScopedSupabase();

  const { error } = await supabase
    .from("ai_conversations")
    .delete()
    .eq("id", id)
    .eq("user_id", userId);

  if (error) {
    console.error("deleteConversation:", error);
    return { success: false, error: error.message };
  }

  revalidatePath("/ai-digest/chat");
  return { success: true };
}

export async function getConversationMessages(
  conversationId: string
): Promise<ActionResult<ConversationMessage[]>> {
  const { supabase, userId } = await getScopedSupabase();

  const { data, error } = await supabase
    .from("ai_conversation_messages")
    .select("id, role, content, created_at")
    .eq("user_id", userId)
    .eq("conversation_id", conversationId)
    .order("created_at", { ascending: true })
    .limit(50);

  if (error) {
    console.error("getConversationMessages:", error);
    return { success: false, error: error.message };
  }

  return { success: true, data: (data ?? []) as ConversationMessage[] };
}

export async function clearConversation(
  conversationId?: string
): Promise<ActionResult> {
  const { supabase, userId } = await getScopedSupabase();

  if (conversationId) {
    // Delete the conversation itself (messages cascade)
    const { error } = await supabase
      .from("ai_conversations")
      .delete()
      .eq("id", conversationId)
      .eq("user_id", userId);

    if (error) {
      console.error("clearConversation:", error);
      return { success: false, error: error.message };
    }
  } else {
    // Legacy: delete all messages for the user
    const { error } = await supabase
      .from("ai_conversation_messages")
      .delete()
      .eq("user_id", userId);

    if (error) {
      console.error("clearConversation:", error);
      return { success: false, error: error.message };
    }
  }

  revalidatePath("/ai-digest/chat");
  return { success: true };
}

// ─── Active projects (for project-scoped chat) ────────────────────────────────

export async function getActiveProjects(): Promise<
  ActionResult<ActiveProject[]>
> {
  const { supabase, userId } = await getScopedSupabase();

  const { data, error } = await supabase
    .from("projects")
    .select("id, project_name")
    .eq("user_id", userId)
    .eq("status", "active")
    .order("project_name", { ascending: true });

  if (error) {
    console.error("getActiveProjects:", error);
    return { success: false, error: error.message };
  }

  return {
    success: true,
    data: (data ?? []).map((p) => ({
      id: p.id,
      project_name: p.project_name ?? "Untitled project",
    })),
  };
}

export async function getFreeDailyChatUsage(): Promise<
  ActionResult<{ used: number; limit: number }>
> {
  const { supabase, userId } = await getScopedSupabase();
  const { data: prefs } = await supabase
    .from("user_preferences")
    .select("timezone")
    .eq("user_id", userId)
    .maybeSingle();

  const used = await countChatExchangesOnLocalDay(
    userId,
    prefs?.timezone as string | null
  );
  return {
    success: true,
    data: { used, limit: WINSTON_FREE_DAILY_MESSAGE_CAP },
  };
}
